//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDatabaseEntities : DbContext
    {
        public HotelDatabaseEntities()
            : base("name=HotelDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Room_Details> Room_Details { get; set; }
        public virtual DbSet<Room_Types> Room_Types { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Rooms_Details> Rooms_Details { get; set; }
        public virtual DbSet<Rooms_Photos> Rooms_Photos { get; set; }
    }
}
